### ISSUE TITLE
Link website logo to home page

### ISSUE THREAD

**Issue by kartik3805** [kartik3805/QuickWiKi#1]
current logo ( QuickWiKi ) is in text form, convert it to a link which redirect to home URL
Preview:

<img width="266" alt="issue1" src="https://user-images.githubusercontent.com/94182623/194540984-c2b04abb-8e74-42f6-929f-fc5c3d9591e2.PNG">

**Comment by gaut2003** [comment]
Please assign this to me.

**Comment by utkarsh2709** [comment]
Hello @kartik3805, Pls assign this issue to me.

**Comment by rk-1620** [comment]
@kartik3805, I would like to work on this issue. Please assign it to me.

**Comment by FixxooXD** [comment]
@kartik3805 hello I had already fixed this issue and created a PR you can review it and  merged if possible

**Comment by kartik3805** [comment]
Issue solved
