### ISSUE TITLE
Unresponsive (too small in size) search bar in mobile device

### ISSUE THREAD

**Issue by kartik3805** [kartik3805/QuickWiKi#2]
Currently search bar is too small in mobile version resize it and make it larger which fits perfectly with mobile devices
Preview:

<img width="296" alt="issue2" src="https://user-images.githubusercontent.com/94182623/194542894-80f7d6f3-30fc-4a10-8bdc-0e899e6521e2.PNG">

**Comment by utkarsh2709** [comment]
Hello @kartik3805, Pls assign this to me. I have worked extensively on responsiveness.

**Comment by kartik3805** [comment]
> Hello @kartik3805, Pls assign this to me. I have worked extensively on responsiveness.

sure

**Comment by vilasrhegde** [comment]
Hey @kartik3805 I have solved this issue and can you proceed with merging? Thanks

**Comment by kartik3805** [comment]
> Hey @kartik3805 I have solved this issue and can you proceed with merging? Thanks

It has some issues please review them

**Comment by vilasrhegde** [comment]
Can I recreate whole styling from scratch in real quick?
@kartik3805

**Comment by kartik3805** [comment]
> Can I recreate whole styling from scratch in real quick? @kartik3805

You can give it a try
