### ISSUE TITLE
Style Improve

### ISSUE THREAD

**Issue by mailmesapna1** [kartik3805/QuickWiKi#21]
hey @kartik3805 i want to work on this issue will you assign it to me

**Comment by mailmesapna1** [comment]
Hey @kartik3805 I want to make a box in it as well box shadow  as it look attractive

**Comment by mailmesapna1** [comment]
Hey @kartik3805 your website look like this

![image](https://user-images.githubusercontent.com/96010017/194619147-7af7d275-2bd1-412a-abaa-b4ea42e49ccd.png)
Will you assign it to me

**Comment by kartik3805** [comment]
Sorry but it is not looking good
