### ISSUE TITLE
Unresponsive content and image in mobile devices

### ISSUE THREAD

**Issue by kartik3805** [kartik3805/QuickWiKi#3]
Currently page content is very unresponsive in mobile devices
Issue Preview:

<img width="292" alt="issue3" src="https://user-images.githubusercontent.com/94182623/194543453-c71d7f0a-eb0f-42e7-8181-63573e8a56fb.PNG">

**Comment by utkarsh2709** [comment]
Hello @kartik3805, Pls assign this to me. I have worked extensively on responsiveness.

**Comment by Amank-root** [comment]
Hi, @kartik3805 could you please assign the issue to me?

**Comment by Yugal308** [comment]
Hi @kartik3805 can you please assign this issue to me as well?

**Comment by vilasrhegde** [comment]
hey @kartik3805 would you check my PR please? I have improved the layout
