### ISSUE TITLE
Remove previous quick wiki, if entered wiki doesn't exist

### ISSUE THREAD

**Issue by mnosov622** [kartik3805/QuickWiKi#32]
Hi !

### If you enter invalid url after you can see quick wiki information, the previous wiki doesn't disappear.

![image](https://user-images.githubusercontent.com/73063742/194929631-0c2c1740-ae91-4469-b057-57c7750d55de.png)

## Steps to reproduce:

1. Enter valid url in the search input (https://en.wikipedia.org/wiki/United_States_Commission_of_Fine_Arts)
2. Enter invalid url in the search input

## Expected Result:

Previous wiki disappears and message "Oops! That article doesn't exists!" is displayed.

## Actual result:

Previous wiki doesn't disappear and message "Oops! That article doesn't exists!" is displayed.

I think it's better to remove the previous wiki, because it will confuse the user. If possible, can you assign this issue to me, please? I would love to fix it.

Thank you!

**Comment by kartik3805** [comment]
Would you like to work on this issue?

**Comment by kartik3805** [comment]
> Hi !
> 
> ### If you enter invalid url after you can see quick wiki information, the previous wiki doesn't disappear.
> ![image](https://user-images.githubusercontent.com/73063742/194929631-0c2c1740-ae91-4469-b057-57c7750d55de.png)
> 
> ## Steps to reproduce:
> 1. Enter valid url in the search input (https://en.wikipedia.org/wiki/United_States_Commission_of_Fine_Arts)
> 2. Enter invalid url in the search input
> 
> ## Expected Result:
> Previous wiki disappears and message "Oops! That article doesn't exists!" is displayed.
> 
> ## Actual result:
> Previous wiki doesn't disappear and message "Oops! That article doesn't exists!" is displayed.
> 
> I think it's better to remove the previous wiki, because it will confuse the user. If possible, can you assign this issue to me, please? I would love to fix it.
> 
> Thank you!

Would you like to work on this issue?

**Comment by mnosov622** [comment]
@kartik3805 Yes, please.

Could you assign it to me, please ?
