### ISSUE TITLE
No margin in 'steps paragraph', in mobile devices

### ISSUE THREAD

**Issue by kartik3805** [kartik3805/QuickWiKi#35]
There is a need to add side margin to steps paragraph in mobile devices, to make it feels more readable and look good

Issue Preview:
<img width="202" alt="issue 8" src="https://user-images.githubusercontent.com/94182623/195302253-6a2516bd-77bb-4c12-95a5-9bc9a2a36b5d.PNG">

**Comment by najeebkp** [comment]
hi @kartik3805 please assign this to me

**Comment by Hussain6** [comment]
@kartik3805 can you assign this to me I would like to contribute to this repo.
