### ISSUE TITLE
Add steps/ guide to use website 

### ISSUE THREAD

**Issue by kartik3805** [kartik3805/QuickWiKi#4]
Add short steps in below blank space, describing steps of procedure to use the website with URL example

Preview:

<img width="735" alt="issue4" src="https://user-images.githubusercontent.com/94182623/194544215-14bed958-c5fc-4dd4-b80b-a8276bc4021a.PNG">

**Comment by aswinikalyan30** [comment]
Hey, can I take this up?

**Comment by MayankUghade** [comment]
**@kartik3805  I would love to this task ,**
I am new to open source so please help me to understand more about the issue, and assign me this task

**Comment by kartik3805** [comment]
> **@kartik3805 I would love to this task ,** I am new to open source so please help me to understand more about the issue, and assign me this task

Steps to use website easily, like copy URL from Wikipedia and then paste in search box.....like that

**Comment by VedVaghela** [comment]
@kartik3805 I would like to contribute to this, could you please assign me this issue

**Comment by manishgupta416** [comment]
Can you assign to me?
I'm new to open source
