### ISSUE TITLE
Error message also shows when there is no error

### ISSUE THREAD

**Issue by kartik3805** [kartik3805/QuickWiKi#50]
Error message box appear even if there is no error
Issue Preview:

![Screenshot (99)](https://user-images.githubusercontent.com/94182623/197142970-516661b3-a10f-4f31-b456-959ac6162696.png)

**Comment by Shivam164** [comment]
Hey @kartik3805, I would like to work on this, please assign this to me.

**Comment by kashish0604** [comment]
hey @kartik3805 can you assign this issue to me i can work on it

**Comment by adityabisoyi** [comment]
Can you assign me this issue?
