### ISSUE TITLE
Front end issue

### ISSUE THREAD

**Issue by dharmikjethva30** [kartik3805/QuickWiKi#6]
![image](https://user-images.githubusercontent.com/97388367/194549567-15e29f37-4bf4-4e1a-918b-e1f4e2428974.png)
Found design issues, would like to fix it.
- Extra white space 
- 'Get quick and short summary for your desired wikipedia article' can be removed when results are given
- Page URL not alinged properly

**Comment by dharmikjethva30** [comment]
please add hactoberfest and hactober-acceped tags

**Comment by kartik3805** [comment]
> please add hactoberfest and hactober-acceped tags

added

**Comment by kashish0604** [comment]
hey @dharmikjethva30 can you assign this issue to me i can work on it

**Comment by kashish0604** [comment]
hey @kartik3805 can you assign this issue to me i can work on it

**Comment by kartik3805** [comment]
Discussed UI changes already implemented
