### ISSUE TITLE
Search topics in URL input field

### ISSUE THREAD

**Issue by balayokesh** [kartik3805/QuickWiKi#66]
## Describe Feature
Hi I found that not only wikipedia article links works, we can also search keywords.  When we input a keyword it automatically finds a wikipedia topic and displays images, short summary, description  
But everywhere in the website it is mentioned only to paste the link.  So I would like to make a pull request changing the description, alert messages, URL input field placeholder to acknowledge user that they can use either URL for wikipedia articles or they can search a topic.
## Is your feature request related to a problem?
- [ ] Yes
- [ ] No
- [x] Not sure

## Additional context
![image](https://user-images.githubusercontent.com/59578892/197823016-d5dacda0-b235-48b3-958f-fa3388bc390d.png)

In the above image I have used the term `Coder` and it automatically fetches a wikipedia article and loads contents about that topic.

**Comment by balayokesh** [comment]
I you are ok with these changes to be implemented please assign this issue to me under hacktoberfest

**Comment by kartik3805** [comment]
> ## Describe Feature
> Hi I found that not only wikipedia article links works, we can also search keywords. When we input a keyword it automatically finds a wikipedia topic and displays images, short summary, description But everywhere in the website it is mentioned only to paste the link. So I would like to make a pull request changing the description, alert messages, URL input field placeholder to acknowledge user that they can use either URL for wikipedia articles or they can search a topic.
> 
> ## Is your feature request related to a problem?
> * [ ]  Yes
> * [ ]  No
> * [x]  Not sure
> 
> ## Additional context
> ![image](https://user-images.githubusercontent.com/59578892/197823016-d5dacda0-b235-48b3-958f-fa3388bc390d.png)
> 
> In the above image I have used the term `Coder` and it automatically fetches a wikipedia article and loads contents about that topic.

Yes, it is a great suggestion please work on this
